// Copies the exact font files Premium templates use from extracted @fontsource
// packages into template-library/fonts/, with licences, and writes fonts.css.
// Usage: node template-library/scripts/vendor-fonts.mjs <dir containing extracted fontsource-*/package>
// Fonts are OFL-1.1; they are bundled with the app/PDF renderer, never uploaded elsewhere.
import { readFile, writeFile, copyFile, mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const source = process.argv[2];
const out = fileURLToPath(new URL('../fonts/', import.meta.url));
// [package dir prefix, css files to take faces from]
const plan = [
 // Newsreader replaces Source Serif 4: Source Serif 4 shares its curly-quote glyphs with
 // U+02BB/U+02BC, so Chromium writes modifier letters into the PDF text layer
 // (copy/paste and parsers see "companyʼs"). See scripts/apostrophe-probe.ts.
 ['fontsource-variable-newsreader', ['opsz.css', 'opsz-italic.css']],
 ['fontsource-variable-source-sans-3', ['wght.css', 'wght-italic.css']],
 ['fontsource-ibm-plex-sans-5', ['400.css', '500.css', '600.css', '700.css', '400-italic.css']],
 ['fontsource-ibm-plex-sans-condensed', ['400.css', '500.css', '600.css', '700.css']],
 ['fontsource-ibm-plex-mono', ['400.css', '500.css']],
 ['fontsource-variable-instrument-sans', ['wdth.css', 'wdth-italic.css']],
 ['fontsource-instrument-serif', ['400.css', '400-italic.css']],
];
await mkdir(out, { recursive: true });
const dirs = await readdir(source);
const faces = [];
const licences = [];
for (const [prefix, cssFiles] of plan) {
 const dir = dirs.find(d => d.startsWith(prefix));
 if (!dir) throw new Error(`missing ${prefix}`);
 const pkg = path.join(source, dir, 'package');
 const meta = JSON.parse(await readFile(path.join(pkg, 'package.json'), 'utf8'));
 const family = meta.name.replace('@fontsource/', '').replace('@fontsource-variable/', '');
 await copyFile(path.join(pkg, 'LICENSE'), path.join(out, `LICENSE-${family}.txt`));
 licences.push(`${meta.name}@${meta.version} — ${meta.license}`);
 for (const cssFile of cssFiles) {
  const css = await readFile(path.join(pkg, cssFile), 'utf8');
  for (const face of css.match(/@font-face\s*{[^}]*}/g) ?? []) {
   const woff2 = face.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
   if (!/-latin-(?:ext-)?(?:\d|wght|opsz|wdth|standard)/.test(woff2)) continue;
   await copyFile(path.join(pkg, 'files', woff2), path.join(out, woff2));
   // One src only (woff2), relative to fonts.css; strip the woff fallback.
   faces.push(face.replace(/src:[^;]+;/, `src: url(./${woff2}) format('woff2');`).replace(/font-display:\s*\w+;/, 'font-display: block;').replace(/ Variable'/, "'"));
  }
 }
}
await writeFile(path.join(out, 'fonts.css'), `/* Generated by scripts/vendor-fonts.mjs — do not edit. Latin + Latin Extended subsets.\n${licences.map(l => ` * ${l}`).join('\n')}\n */\n${faces.join('\n')}\n`);
console.log(`${faces.length} faces from ${licences.length} packages → ${out}`);
