import { useEffect, useRef, useState } from 'react';
import { supabase } from '../../services/supabase';
import { trackProductEvent } from '../../services/analytics';

type Subscription = { subscriptionId:string; offerKey:string; kind:'pro'|'template'; templateId:string|null; status:string; cancelAtPeriodEnd:boolean; currentPeriodEnd:string|null };
type BillingStatus = { isPro:boolean; activeTemplates:string[]; subscriptions:Subscription[]; salesAvailable:boolean };

async function serverMessage(response:Response) { try { const body=await response.json(); return typeof body?.error==='string'?body.error:''; } catch { return ''; } }

export function BillingPanel({ ownerId, surface='account' }: { ownerId:string; surface?:'account'|'purchase' }) {
 const [status,setStatus]=useState<BillingStatus|null>(null),[message,setMessage]=useState('Checking billing…');
 const [consent,setConsent]=useState(false),[busy,setBusy]=useState(false);const active=useRef(true),requestId=useRef(crypto.randomUUID());
 useEffect(()=>{active.current=true;const controller=new AbortController();(async()=>{try{const {data}=await supabase!.auth.getSession();if(data.session?.user.id!==ownerId)return;const response=await fetch('/api/subscription-status',{headers:{Authorization:`Bearer ${data.session.access_token}`},signal:controller.signal});if(!response.ok)throw new Error();const value=await response.json() as BillingStatus;if(typeof value.isPro!=='boolean'||typeof value.salesAvailable!=='boolean'||!Array.isArray(value.activeTemplates)||!Array.isArray(value.subscriptions))throw new Error();if(!controller.signal.aborted){setStatus(value);setMessage('');}}catch{if(!controller.signal.aborted)setMessage('Billing details are temporarily unavailable. Your resume remains available.');}})();return()=>{active.current=false;controller.abort();};},[ownerId]);
 async function authorizedPost(path:string,body:unknown){const {data}=await supabase!.auth.getSession();if(data.session?.user.id!==ownerId)throw new Error('Sign in again');const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify(body)});if(!response.ok)throw new Error(await serverMessage(response)||'Request could not be completed.');return response.json();}
 async function start(){if(busy||!consent||!status?.salesAvailable)return;setBusy(true);setMessage('');try{const result=await authorizedPost('/api/subscription-checkout',{requestId:requestId.current,offerKey:'pro:monthly',renewalConsent:true,overlapConsent:status.activeTemplates.length>0});const destination=new URL(result.url);if(destination.origin!=='https://checkout.stripe.com')throw new Error();trackProductEvent('checkout_started',{surface:surface==='purchase'?'pricing':'account',user_state:'authenticated',plan:'Pro'});window.location.assign(destination.href);}catch(error){if(active.current)setMessage(error instanceof Error&&error.message?error.message:'Checkout could not open.');}finally{if(active.current)setBusy(false);}}
 async function portal(){if(busy)return;setBusy(true);setMessage('');try{const result=await authorizedPost('/api/customer-portal',{});const destination=new URL(result.url);if(destination.protocol!=='https:')throw new Error();window.location.assign(destination.href);}catch(error){if(active.current)setMessage(error instanceof Error&&error.message?error.message:'The billing portal could not open.');}finally{if(active.current)setBusy(false);}}
 if(!status)return surface==='purchase'?<section className="billing-panel" aria-label="Secure checkout"><h2>Secure checkout</h2><p role="status">{message}</p></section>:null;
 const activeSubscriptions=status.subscriptions.filter(item=>['active','trialing','past_due','unpaid'].includes(item.status));const pro=activeSubscriptions.find(item=>item.kind==='pro');
 return <section className="billing-panel" aria-label="Plan and billing"><h2>{surface==='purchase'?'Start Pro':'Plan and billing'}</h2>
  {status.isPro?<><p>You have Pro access across all templates.</p>{pro&&<p>{pro.cancelAtPeriodEnd?`Automatic renewal is off. Access continues through ${pro.currentPeriodEnd?new Date(pro.currentPeriodEnd).toLocaleDateString(): 'the paid period'}.`:`Renews monthly at US$19.99 until cancelled${pro.currentPeriodEnd?`, next on ${new Date(pro.currentPeriodEnd).toLocaleDateString()}`:''}.`}</p>}<button className="button outline" disabled={busy} onClick={portal}>{busy?'Opening…':'Manage billing and cancellation'}</button></>
  :<><p>You’re on the Free plan.</p>{status.activeTemplates.length>0&&<p className="helper-box"><strong>Pro includes every Premium template.</strong> After Pro’s first payment succeeds, future renewals for your {status.activeTemplates.length} individual template subscription{status.activeTemplates.length===1?'':'s'} will be stopped. Their already-paid access remains through each paid period.</p>}<p>US$19.99/month. Pro includes all Premium templates, PDF and editable DOCX downloads, Match Analysis, and tailoring. It renews automatically until cancelled.</p><label className="checkbox-field"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/>I agree to a recurring US$19.99 monthly subscription. I can cancel anytime; access continues through the paid billing period.</label><button className="button" disabled={!consent||busy||!status.salesAvailable} onClick={start}>{busy?'Opening secure checkout…':'Start Pro — US$19.99/month'}</button>{!status.salesAvailable&&<p className="field-hint">New paid subscriptions are not available right now.</p>}</>}
  {activeSubscriptions.some(item=>item.kind==='template')&&<button className="button outline" disabled={busy} onClick={portal}>Manage individual template subscriptions</button>}
  {message&&<p role="status">{message}</p>}<p className="field-hint">Available for new subscriptions in the United States. Cancel anytime. Statutory and payment-network rights always apply. Review our <a href="/terms.html">terms and refund policy</a>.</p>
 </section>;
}
