export type Guide = {
 slug: string;
 title: string;
 seoTitle: string;
 description: string;
 eyebrow: string;
 deck: string;
 directAnswer: string;
 sections: Array<{ id: string; title: string; html: string }>;
 related: string[];
 cta: { label: string; href: string; destination: string; note: string };
};

export const resourcesPath = '/resources/';

export const guides: Guide[] = [
 {
  slug: 'tailor-resume-to-job-description',
  title: 'How to tailor a resume to a job description',
  seoTitle: 'How to tailor a resume to a job description | ResumeStride',
  description: 'Tailor your resume by mapping the role’s real requirements to evidence you already have—without rewriting everything or adding unsupported claims.',
  eyebrow: 'A practical, evidence-first method',
  deck: 'Turn a long job posting into a focused resume by changing the emphasis—not the truth.',
  directAnswer: '<p>Read the job description for priorities, not just repeated words. Separate essential requirements from preferences, find the strongest real evidence for each priority, then move, trim or clarify that evidence in a separate copy of your resume. Keep your master resume unchanged.</p>',
  sections: [
   { id: 'read', title: '1. Read the role in three passes', html: `<p>Trying to edit while you read usually produces scattered changes. First understand the role.</p><ol><li><strong>Purpose:</strong> What outcome is this person hired to create?</li><li><strong>Requirements:</strong> Which qualifications appear mandatory, preferred or unclear?</li><li><strong>Language:</strong> Which specific tools, methods, customers or domains does the employer name?</li></ol><p>A phrase appearing several times can signal importance, but repetition alone is not proof that it belongs in your resume. It still needs to describe something you have actually done or learned. The free <a href="/tools/job-requirement-extractor/" data-content-cta="requirement_extractor">job requirement extractor</a> can create a traceable first pass while keeping ambiguous wording ambiguous.</p>` },
   { id: 'map', title: '2. Build a requirement-to-evidence map', html: `<p>For each central requirement, point to evidence in your work, education, projects, research, volunteering or caregiving. Use four honest labels:</p><div class="evidence-grid"><div><strong>Demonstrated</strong><span>Your resume already shows clear evidence.</span></div><div><strong>Present but hidden</strong><span>You have evidence, but the current wording obscures it.</span></div><div><strong>Adjacent</strong><span>You have comparable experience, not the exact item.</span></div><div><strong>Gap</strong><span>You cannot support the requirement yet.</span></div></div><p>A gap is useful information. It may affect whether you apply, what you learn next or what you explain in a cover letter. It is not an instruction to insert the missing phrase.</p>` },
   { id: 'edit', title: '3. Edit in order of impact', html: `<p>Start where readers get the most context:</p><ul><li>Clarify the target role in your headline or summary only if it accurately fits your background.</li><li>Move the most relevant roles, projects or bullets into easier view.</li><li>Rewrite vague bullets so they show the work, scope and result.</li><li>Name a tool or method when you genuinely used it and the detail helps.</li><li>Trim material that competes with stronger evidence for this role.</li></ul><p>Dates, employers, credentials and outcomes do not change just because the posting uses different language.</p>` },
   { id: 'example', title: 'Before and after: clearer evidence, same experience', html: `<div class="example"><p><span>Job priority</span>Coordinate customer onboarding across sales and support.</p><p><span>Before</span>Helped new customers and worked with other teams.</p><p><span>After</span>Coordinated onboarding for new business accounts with sales and support, maintained handoff notes, and resolved setup questions.</p></div><p>The revision does not add a team size, result or software the applicant cannot prove. It makes the existing coordination work visible using accurate language from the role.</p>` },
   { id: 'final-check', title: 'A ten-minute final check', html: `<ul class="checklist"><li>Can every claim be explained with a real example?</li><li>Are the role’s most important requirements easy to find?</li><li>Did you preserve required dates, qualifications and context?</li><li>Does the resume still sound like you?</li><li>Is this saved as a separate job-specific version?</li><li>Would the document make sense without the job posting beside it?</li></ul><aside class="callout"><strong>What not to do</strong><p>Do not paste a list of “missing keywords,” hide text, rename yourself to an inaccurate title or turn exposure into expertise. A closer word match is not worth a weaker interview conversation.</p></aside>` },
  ],
  related: ['compare-resume-to-job-description', 'how-much-resume-should-change', 'tailor-resume-without-lying'],
  cta: { label: 'Compare your resume with a role', href: '/tools/resume-job-match/', destination: 'resume_job_match', note: 'Start with a private, limited evidence check—no account or score required.' },
 },
 {
  slug: 'should-you-tailor-resume-for-every-job',
  title: 'Should you tailor your resume for every job?',
  seoTitle: 'Should you tailor your resume for every job? | ResumeStride',
  description: 'Decide when a job deserves a fully tailored resume, a light role-family edit or no application at all—with a practical effort framework.',
  eyebrow: 'A realistic answer for a real job search',
  deck: 'Tailor for every serious application, but do not give every posting the same amount of time.',
  directAnswer: '<p>You should review your resume against every job you seriously apply for. That does not mean rebuilding it every time. Use a light edit for similar roles, a deeper tailored version for high-priority or meaningfully different roles, and skip postings where a hard requirement or the work itself makes the opportunity a poor fit.</p>',
  sections: [
   { id: 'three-levels', title: 'Use three levels of tailoring', html: `<div class="decision-table"><div><strong>Quick check</strong><span>Same role family and similar priorities</span><p>Confirm the strongest evidence is visible; adjust the headline, summary or bullet order only if needed.</p></div><div><strong>Focused edit</strong><span>A role you genuinely want</span><p>Map its main requirements, clarify several bullets and trim competing detail.</p></div><div><strong>Fresh version</strong><span>Different function, seniority or domain</span><p>Build from your master resume so the story, evidence order and selected projects fit the new direction.</p></div></div>` },
   { id: 'worth-it', title: 'When deeper tailoring is worth the effort', html: `<ul><li>The role is unusually close to your goals or experience.</li><li>The application is likely to receive a careful human review.</li><li>You are changing occupation, industry, seniority or the type of customer you serve.</li><li>Your most relevant evidence is real but buried in the current version.</li><li>The posting asks for a portfolio, selection criteria or specific examples.</li></ul><p>For several near-identical roles, a strong role-family resume can be a useful starting point. Still review each posting for a hard requirement, different emphasis or terminology that genuinely describes your work.</p>` },
   { id: 'skip', title: 'When not to spend an hour tailoring', html: `<p>Do not polish your way around a legal licence, work authorization condition, required language level or other clear eligibility barrier you do not meet. Also pause when the responsibilities, location, schedule or compensation do not work for you. Tailoring cannot repair a role you would not accept.</p><aside class="callout"><strong>Protect your time</strong><p>Set a time box before you begin. If you cannot find credible evidence for the central work after a careful comparison, use that information to make an application decision instead of endlessly rewriting.</p></aside>` },
   { id: 'workflow', title: 'A sustainable weekly workflow', html: `<ol><li>Keep one detailed master resume.</li><li>Group your target roles into a small number of genuine role families.</li><li>Create a strong baseline for each family from the master.</li><li>For every serious application, check hard requirements and top responsibilities.</li><li>Make only the changes that improve relevance or clarity.</li><li>Save the submitted version with the job so you know what the employer saw.</li></ol>` },
   { id: 'mistakes', title: 'Mistakes that create work without adding value', html: `<ul class="checklist"><li>Rewriting every sentence when the role is nearly identical</li><li>Changing wording only to chase a keyword count</li><li>Letting tailored files replace the master resume</li><li>Editing before deciding whether the role fits</li><li>Sending an unreviewed AI rewrite that adds claims or changes your voice</li></ul>` },
  ],
  related: ['how-much-resume-should-change', 'master-resume-vs-tailored-resume', 'tailor-resume-to-job-description'],
  cta: { label: 'See what your resume already demonstrates', href: '/?jobs=1', destination: 'match', note: 'Use Match Analysis as an evidence review—not an interview prediction.' },
 },
 {
  slug: 'compare-resume-to-job-description',
  title: 'How to compare your resume to a job description',
  seoTitle: 'How to compare your resume to a job description | ResumeStride',
  description: 'Compare a resume with a job description using a requirement-to-evidence table, not a misleading keyword percentage or interview prediction.',
  eyebrow: 'A manual comparison you can trust',
  deck: 'The useful question is not “What is my match score?” It is “What can my resume actually demonstrate?”',
  directAnswer: '<p>Break the posting into individual requirements, label each as required, preferred or contextual, and connect it to a specific line in your resume. Mark evidence as clear, partial, absent or genuinely incompatible. Then decide whether to clarify the resume, find better evidence, accept a gap or skip the role.</p>',
  sections: [
   { id: 'extract', title: 'Turn the posting into a short requirement list', html: `<p>Job descriptions mix outcomes, tasks, qualifications and company language. Reduce the posting to items you can evaluate:</p><ul><li><strong>Eligibility and hard constraints:</strong> licence, work authorization, location, schedule or required credential.</li><li><strong>Core work:</strong> the outcomes and responsibilities the person will own.</li><li><strong>Tools and domain knowledge:</strong> software, methods, customers, regulations or subject matter.</li><li><strong>Preferences:</strong> useful advantages that are not stated as minimums.</li></ul><p>Combine duplicate ideas. “Partner with sales,” “work cross-functionally” and “manage stakeholder handoffs” may describe one central collaboration requirement rather than three separate boxes. If the posting is long, use the <a href="/tools/job-requirement-extractor/" data-content-cta="requirement_extractor">free requirement extractor</a> and verify every result against its source text.</p>` },
   { id: 'matrix', title: 'Make a requirement-to-evidence table', html: `<div class="matrix" role="table" aria-label="Example requirement to evidence comparison"><div role="row"><strong role="columnheader">Requirement</strong><strong role="columnheader">Resume evidence</strong><strong role="columnheader">Status</strong></div><div role="row"><span>Run monthly reporting</span><span>Prepared weekly service reports and presented trends</span><span>Adjacent</span></div><div role="row"><span>Advanced Excel</span><span>Built pivot-table reporting workbook</span><span>Demonstrated</span></div><div role="row"><span>Professional licence</span><span>No licence held</span><span>Gap</span></div></div><p>“Adjacent” is not automatically weak. Weekly reporting may be credible evidence for monthly reporting. But it should not be relabelled “five years of monthly reporting” if that did not happen.</p>` },
   { id: 'interpret', title: 'Interpret the gaps instead of counting them', html: `<p>Ten minor preferences do not necessarily outweigh one central requirement. One missing legal credential may matter more than ten demonstrated soft skills. Rank the gaps by consequence:</p><ol><li>Does it affect eligibility or safe/legal performance?</li><li>Is it central to the day-to-day work?</li><li>Could adjacent experience transfer?</li><li>Could it reasonably be learned after starting?</li><li>Does the posting call it required, preferred or simply mention it?</li></ol><p>This produces a decision you can explain. A percentage collapses those different questions into one number.</p>` },
   { id: 'actions', title: 'Choose one action for each item', html: `<ul><li><strong>Keep:</strong> the evidence is already clear.</li><li><strong>Clarify:</strong> accurate experience is present but vague.</li><li><strong>Add:</strong> relevant real evidence exists elsewhere in your master resume.</li><li><strong>Explain:</strong> adjacent experience needs context in a cover letter or application answer.</li><li><strong>Accept the gap:</strong> apply without pretending to have it.</li><li><strong>Stop:</strong> a hard constraint makes the role unsuitable.</li></ul>` },
   { id: 'check', title: 'What a good comparison leaves you with', html: `<ul class="checklist"><li>A short, prioritized requirement list</li><li>A real resume line beside every supported requirement</li><li>Uncertain items kept uncertain</li><li>Gaps visible enough to inform your decision</li><li>A small set of justified edits—not a wall of suggested keywords</li></ul>` },
  ],
  related: ['how-to-know-if-qualified-for-job', 'resume-keywords', 'tailor-resume-to-job-description'],
  cta: { label: 'Check your evidence now', href: '/tools/resume-job-match/', destination: 'resume_job_match', note: 'Paste plain text for a private, limited comparison before deciding what to edit.' },
 },
 {
  slug: 'how-to-know-if-qualified-for-job',
  title: 'How to know if you’re qualified for a job',
  seoTitle: 'How to know if you’re qualified for a job | ResumeStride',
  description: 'Evaluate job qualifications without arbitrary percentage rules: check eligibility, core work, evidence, transferable experience and genuine gaps.',
  eyebrow: 'A better answer than “meet 60% and apply”',
  deck: 'Qualification is not a single percentage. Start with hard constraints, then judge whether your evidence supports the work.',
  directAnswer: '<p>You are plausibly qualified when you meet the true eligibility requirements and can show credible evidence for much of the role’s central work—even if your path, title or tools are not identical. Treat licences, legal eligibility and explicit minimums differently from preferences. Do not rely on a universal percentage rule.</p>',
  sections: [
   { id: 'four-questions', title: 'Ask four questions in order', html: `<ol><li><strong>Am I eligible?</strong> Check work authorization, location, schedule, licence and other explicit constraints.</li><li><strong>Can I do the central work?</strong> Translate the posting into outcomes and recurring responsibilities.</li><li><strong>Can I demonstrate that?</strong> Find examples in employment, projects, education, research, volunteering or other relevant experience.</li><li><strong>What is missing?</strong> Separate learnable gaps, presentational gaps and true blockers.</li></ol><p>Eligibility and qualification are not always the same. In some hiring systems—especially regulated or government roles—failing an eligibility condition can end review before the strength of your broader experience is considered.</p>` },
   { id: 'hard-soft', title: 'Separate hard constraints from flexible signals', html: `<div class="comparison"><div><strong>Usually hard</strong><ul><li>Required professional licence</li><li>Legal work eligibility</li><li>Mandatory security clearance already held</li><li>Essential language or location condition</li></ul></div><div><strong>Often needs judgment</strong><ul><li>Exact years of experience</li><li>A preferred degree</li><li>A closely related software tool</li><li>An unfamiliar but transferable industry</li></ul></div></div><p>The wording and occupation matter. “Preferred” is not “required.” But do not assume every stated minimum is optional merely because another employer might be flexible.</p>` },
   { id: 'scenario', title: 'A realistic scenario', html: `<p>A community-program coordinator role asks for event planning, partner communication, budget tracking and three years in a nonprofit. You have two years coordinating university events, managed small budgets and worked with local partners, but have not worked for a nonprofit.</p><p>You have direct evidence for the core work, a modest experience gap and a domain gap—not zero qualification. A reasonable application would make the coordination, budgets and partners easy to see while leaving the nonprofit gap honest. A claim that your university role “was nonprofit management” would not be reasonable.</p>` },
   { id: 'apply', title: 'Apply, investigate or move on?', html: `<div class="decision-table"><div><strong>Apply</strong><span>Core work is supported</span><p>You meet hard requirements and can demonstrate central responsibilities.</p></div><div><strong>Investigate</strong><span>Wording is ambiguous</span><p>Look for an official careers page, contact the recruiter where appropriate, or use the application to explain adjacent evidence.</p></div><div><strong>Move on</strong><span>A true blocker remains</span><p>You lack an explicit licence, eligibility condition or central capability and cannot credibly bridge it.</p></div></div>` },
   { id: 'avoid', title: 'Avoid both extremes', html: `<aside class="callout"><strong>Do not reject yourself too quickly</strong><p>Different titles and tools can hide highly transferable work. Compare responsibilities and outcomes, not labels alone.</p></aside><aside class="callout warning"><strong>Do not apply by denial</strong><p>Interest is not evidence. If the role’s essential work is mostly unfamiliar, use it as a development map rather than changing your resume to appear qualified.</p></aside>` },
  ],
  related: ['compare-resume-to-job-description', 'resume-keywords', 'tailor-resume-without-lying'],
  cta: { label: 'See what your resume demonstrates', href: '/?jobs=1', destination: 'match', note: 'Use evidence beside each requirement to make your own application decision.' },
 },
 {
  slug: 'master-resume-vs-tailored-resume',
  title: 'Master resume vs. tailored resume',
  seoTitle: 'Master resume vs. tailored resume: what to keep in each | ResumeStride',
  description: 'Learn the difference between a complete master resume and a focused tailored resume, what belongs in each and how to keep versions organized.',
  eyebrow: 'One career record, many focused versions',
  deck: 'Your master resume preserves the full record. A tailored resume selects the evidence that matters for one role.',
  directAnswer: '<p>A master resume is your private, detailed source document. It can be longer and include experience you will not send every time. A tailored resume is a separate, focused version for one role or close role family. Build tailored versions from the master; never let a short application file become the only record of your experience.</p>',
  sections: [
   { id: 'difference', title: 'The difference at a glance', html: `<div class="matrix" role="table" aria-label="Master and tailored resume comparison"><div role="row"><strong role="columnheader">Question</strong><strong role="columnheader">Master resume</strong><strong role="columnheader">Tailored resume</strong></div><div role="row"><span>Who is it for?</span><span>You</span><span>One employer or role family</span></div><div role="row"><span>What does it include?</span><span>Your useful career evidence</span><span>The most relevant, supported evidence</span></div><div role="row"><span>How long?</span><span>As long as needed to preserve detail</span><span>As concise as the context requires</span></div><div role="row"><span>Does it get submitted?</span><span>Usually no</span><span>Yes, after review</span></div></div>` },
   { id: 'master', title: 'What belongs in the master resume', html: `<ul><li>Roles, projects, education, training, certifications and volunteering</li><li>Fuller accomplishment notes, scope, tools and outcomes</li><li>Different kinds of work that support different future directions</li><li>Accurate dates, titles and context you do not want to reconstruct later</li><li>Prompts for evidence you still need to verify or quantify</li></ul><p>The master is not a dumping ground for private data. It still does not need government ID numbers, banking information, irrelevant confidential material or claims you cannot support.</p>` },
   { id: 'tailored', title: 'What changes in a tailored resume', html: `<ul><li>The order and space given to relevant sections</li><li>Which bullets, projects or skills are included</li><li>How clearly the summary connects your real background to the role</li><li>Terminology where the employer’s wording accurately describes your experience</li><li>Details that are trimmed because they distract from stronger evidence</li></ul><p>The facts do not change: dates, credentials, employers, responsibility level and results must remain accurate.</p>` },
   { id: 'system', title: 'A simple version system', html: `<ol><li>Update the master when you gain or remember useful evidence.</li><li>Duplicate it before any job-specific edits.</li><li>Name the version with the role and employer, not “resume-final-final.”</li><li>Keep a copy of exactly what you submitted.</li><li>Return new verified details to the master so future versions improve.</li></ol><div class="example"><p><span>Master</span>resumestride-master-2026.docx</p><p><span>Submitted version</span>alex-chen-operations-coordinator-northstar.pdf</p></div>` },
   { id: 'failure', title: 'When one document tries to do both jobs', html: `<p>A “universal” resume often becomes crowded because it tries to support every direction at once. The opposite failure is also common: a tailored resume gets overwritten repeatedly until earlier evidence disappears. Separating the two documents solves both problems—breadth stays in the master; focus belongs in the application version.</p>` },
  ],
  related: ['should-you-tailor-resume-for-every-job', 'how-much-resume-should-change', 'tailor-resume-to-job-description'],
  cta: { label: 'Build your master resume', href: '/?builder=1', destination: 'builder', note: 'Create the foundation first, then keep job-specific versions separate.' },
 },
 {
  slug: 'how-much-resume-should-change',
  title: 'How much of your resume should change for each job?',
  seoTitle: 'How much should your resume change for each job? | ResumeStride',
  description: 'Learn what to change, what to keep fixed and when a resume needs a light edit versus a deeper job-specific version.',
  eyebrow: 'Change relevance, not identity',
  deck: 'There is no honest percentage. The amount should follow how different the role is from your current resume’s focus.',
  directAnswer: '<p>Change only what improves relevance or clarity. For a similar role, that may mean reordering a few bullets and adjusting the summary. For a career shift, you may select different projects and substantially change the emphasis. Keep factual identity, dates, credentials, employers and outcomes fixed.</p>',
  sections: [
   { id: 'layers', title: 'Think in three layers', html: `<div class="decision-table"><div><strong>Fixed facts</strong><span>Do not tailor</span><p>Contact details, employers, dates, credentials, job level and verified outcomes.</p></div><div><strong>Selected evidence</strong><span>Tailor most often</span><p>Bullets, projects, skills, ordering and the space each experience receives.</p></div><div><strong>Framing</strong><span>Tailor carefully</span><p>Headline and summary, using language that remains accurate and natural.</p></div></div>` },
   { id: 'distance', title: 'Let role distance determine the work', html: `<ul><li><strong>Same work, similar setting:</strong> run a requirement check; make a few targeted edits.</li><li><strong>Same function, new industry:</strong> surface transferable outcomes and relevant domain exposure.</li><li><strong>New function:</strong> choose different evidence from the master and explain the connection more deliberately.</li><li><strong>New seniority:</strong> emphasize the real scope of decisions, leadership and accountability—without inflating titles or team size.</li></ul>` },
   { id: 'examples', title: 'What a light edit and deeper edit look like', html: `<div class="comparison"><div><strong>Light edit: support role → support role</strong><p>Move the bullet about handling escalations higher, name the ticketing tool already used, and trim an unrelated stockroom task.</p></div><div><strong>Deeper edit: teacher → learning designer</strong><p>Lead with curriculum projects, learner research, facilitation and content evaluation; reduce routine classroom administration. Do not rename teaching experience as a learning-designer job.</p></div></div>` },
   { id: 'stop', title: 'Know when to stop editing', html: `<p>Your version is ready when a reader can quickly understand:</p><ul class="checklist"><li>What direction you are pursuing</li><li>Which past evidence supports the central work</li><li>What scope and outcomes you can credibly discuss</li><li>Where any important gap remains</li></ul><p>It is not ready merely because every phrase from the job posting appears somewhere. More edits can make the document less coherent, less human and harder to defend.</p>` },
   { id: 'never', title: 'What should never change', html: `<aside class="callout warning"><strong>The truth boundary</strong><p>Never change a date, title, credential, client type, tool proficiency, team size or result to resemble the posting. If the only way to make a resume look aligned is to alter a fact, the role is revealing a gap—not an editing task.</p></aside>` },
  ],
  related: ['should-you-tailor-resume-for-every-job', 'master-resume-vs-tailored-resume', 'tailor-resume-without-lying'],
  cta: { label: 'Create a separate job-specific version', href: '/?jobs=1', destination: 'tailoring', note: 'Start from your master and keep the original unchanged.' },
 },
 {
  slug: 'resume-keywords',
  title: 'Resume keywords: what actually belongs in your resume',
  seoTitle: 'Resume keywords: what actually belongs in your resume | ResumeStride',
  description: 'Choose resume keywords that describe real skills, tools, methods and qualifications—and place them where your evidence supports them.',
  eyebrow: 'Use the language of the work, not a keyword dump',
  deck: 'A keyword belongs when it accurately names something you can demonstrate and helps a reader understand your fit.',
  directAnswer: '<p>Use specific job titles, tools, methods, certifications, domain terms and skills when they truthfully describe your experience. Put them beside evidence—in a bullet, project, education entry or accurate skills section. Do not add every term in a posting, hide keywords or treat a target percentage as proof of qualification.</p>',
  sections: [
   { id: 'types', title: 'Five useful kinds of resume keyword', html: `<ul><li><strong>Role and function:</strong> customer success, payroll, laboratory technician, curriculum design</li><li><strong>Tools and systems:</strong> Excel, Salesforce, AutoCAD, Kubernetes</li><li><strong>Methods and processes:</strong> root-cause analysis, month-end close, usability testing</li><li><strong>Domain knowledge:</strong> food safety, public procurement, SaaS onboarding</li><li><strong>Verified qualifications:</strong> degrees, licences, certifications and language proficiency</li></ul><p>Action verbs can improve writing, but a generic verb such as “managed” does not replace the specific object, scope and evidence of the work. The <a href="/tools/job-requirement-extractor/" data-content-cta="requirement_extractor">job requirement extractor</a> can separate stated requirements from other signals without turning every repeated word into a mandate.</p>` },
   { id: 'test', title: 'The evidence test', html: `<p>Before adding a term, answer three questions:</p><ol><li>Does this phrase accurately describe something I did, learned or earned?</li><li>Can I point to where the resume demonstrates it?</li><li>Could I discuss it comfortably in an interview?</li></ol><p>If the answer is no, leave it out. If the experience is real but the term is new, learn what the employer means before deciding that the wording is equivalent.</p>` },
   { id: 'placement', title: 'Put each term where it earns credibility', html: `<div class="example"><p><span>Weak</span>Skills: stakeholder management, process improvement, Salesforce</p><p><span>Stronger</span>Mapped the support handoff with sales and operations, then rebuilt the Salesforce intake fields to reduce incomplete requests.</p></div><p>The stronger line connects the terms to a real action and context. A skills section can still help with quick scanning, but it should not be the only evidence for a central capability.</p>` },
   { id: 'translation', title: 'Translate accurately, not mechanically', html: `<p>A posting may say “client relationship management” while your resume says “supported member accounts.” If the work genuinely involved ongoing relationships, the employer’s language may make the connection clearer. If you only answered one-time questions, the broader phrase may overstate the work.</p><p>Use both a full name and common abbreviation once when it aids understanding—for example, “Search Engine Optimization (SEO)”—but do not create awkward repetitions throughout the document.</p>` },
   { id: 'avoid', title: 'Keyword practices to avoid', html: `<ul class="checklist"><li>A visible “keywords” paragraph with no context</li><li>White text, tiny type or off-page terms</li><li>Repeating a phrase until the resume sounds unnatural</li><li>Copying soft-skill adjectives without examples</li><li>Listing exposure to a tool as proficiency</li><li>Using a keyword score as a prediction of interviews</li></ul><aside class="callout"><strong>A better success test</strong><p>A hiring reader should be able to find the relevant term, understand what you did with it and see why it matters—without needing the job description open beside your resume.</p></aside>` },
  ],
  related: ['compare-resume-to-job-description', 'tailor-resume-to-job-description', 'tailor-resume-without-lying'],
  cta: { label: 'Extract the role’s requirements', href: '/tools/job-requirement-extractor/', destination: 'requirement_extractor', note: 'Find source-backed terms worth reviewing, then keep only the ones your experience supports.' },
 },
 {
  slug: 'tailor-resume-without-lying',
  title: 'How to tailor a resume without making things up',
  seoTitle: 'How to tailor a resume without lying or making things up | ResumeStride',
  description: 'Tailor your resume honestly by clarifying, selecting and translating real experience—without inventing skills, titles, results or credentials.',
  eyebrow: 'Make the evidence clearer. Keep every claim defensible.',
  deck: 'Honest tailoring changes what you emphasize. Fabrication changes what happened.',
  directAnswer: '<p>Start from facts you can verify, then select the most relevant examples, translate unfamiliar wording carefully and add missing context you genuinely remember. Do not invent employers, titles, tools, results, dates, credentials or responsibility. When evidence is adjacent rather than exact, describe the connection instead of erasing the gap.</p>',
  sections: [
   { id: 'boundary', title: 'The line between tailoring and fabrication', html: `<div class="comparison"><div><strong>Honest tailoring</strong><ul><li>Moving a relevant project higher</li><li>Naming a tool you actually used</li><li>Clarifying who you supported</li><li>Removing less relevant detail</li><li>Using an accurate industry synonym</li></ul></div><div><strong>Fabrication</strong><ul><li>Changing your title to a role you did not hold</li><li>Adding a tool you only saw in the posting</li><li>Inventing a metric or customer count</li><li>Extending dates to hide a gap</li><li>Claiming an unearned credential</li></ul></div></div>` },
   { id: 'ladder', title: 'Use an evidence ladder', html: `<p>Describe each item at the highest level you can honestly support:</p><ol><li><strong>Owned:</strong> you were accountable for the work or result.</li><li><strong>Performed:</strong> you completed the work yourself.</li><li><strong>Contributed:</strong> you had a defined part in a shared effort.</li><li><strong>Observed or learned:</strong> you received training or exposure but did not perform it independently.</li><li><strong>Not experienced:</strong> leave it out or name it as a development goal outside the resume.</li></ol><p>Problems begin when “observed” becomes “performed,” or “contributed” becomes “led.” Precise verbs protect both credibility and confidence.</p>` },
   { id: 'example', title: 'Before and after: accurate translation', html: `<div class="example"><p><span>Posting</span>Lead cross-functional incident reviews and drive corrective actions.</p><p><span>Real experience</span>You gathered customer reports, reproduced issues and joined reviews run by engineering.</p><p><span>Honest version</span>Investigated customer-reported issues, documented reproduction steps, and contributed customer context to engineering incident reviews.</p><p><span>Dishonest version</span>Led cross-functional incident response and owned corrective-action delivery.</p></div>` },
   { id: 'unknowns', title: 'What to do when you do not know the number', html: `<p>Specific results are useful only when they are real. If you cannot verify a percentage, revenue figure or volume:</p><ul><li>Use a scope you do know: region, process, audience or frequency.</li><li>Describe the observable outcome without manufacturing precision.</li><li>Check reliable records if you still have access and are allowed to use them.</li><li>Leave the number out when uncertainty remains.</li></ul><p>“Reduced recurring setup errors by standardizing the checklist” is more credible than an invented “reduced errors by 47%.” The <a href="/tools/resume-bullet-checker/" data-content-cta="bullet_checker">free bullet checker</a> will ask for missing evidence rather than manufacture it.</p>` },
   { id: 'ai', title: 'Review AI suggestions like an editor', html: `<p>An AI-generated sentence is not evidence. For every proposed change, ask:</p><ul class="checklist"><li>Which original fact supports this claim?</li><li>Did the verb increase my responsibility?</li><li>Did it add a result, number, tool or audience?</li><li>Did it remove context that changes the meaning?</li><li>Would I say this aloud in an interview?</li></ul><aside class="callout"><strong>Your decision stays final</strong><p>Accept only the parts that preserve your meaning. Reject or rewrite anything that sounds impressive because it moved beyond the source evidence.</p></aside>` },
   { id: 'gap', title: 'Let a real gap remain a gap', html: `<p>If a required skill is absent, you still have choices: apply with adjacent evidence, explain active learning, seek a more suitable role or build the skill through real work. The one choice that does not help is inserting the phrase and hoping no one asks. A private <a href="/tools/resume-job-match/" data-content-cta="resume_job_match">resume vs. job evidence check</a> can help you keep “not demonstrated” separate from “confirmed incompatible.”</p>` },
  ],
  related: ['tailor-resume-to-job-description', 'resume-keywords', 'how-to-know-if-qualified-for-job'],
  cta: { label: 'Check one resume bullet', href: '/tools/resume-bullet-checker/', destination: 'bullet_checker', note: 'Get transparent feedback without invented metrics, tools or outcomes.' },
 },
];

export const guideBySlug = new Map(guides.map(guide => [guide.slug, guide]));
