import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, Download, FileText, Globe2, GripVertical, LayoutTemplate, Menu, Plus, RotateCcw, ShieldCheck, Sparkles, Trash2, Upload, UserRound, X } from 'lucide-react';
import { blank, entry, example, isResume, migrate, rescueKey, storageKey, type Resume } from './model';
import { ResumePreview } from './components/ResumePreview';
import './styles.css';
function initial(): {resume:Resume; warning:string; rescue:string|null} {
 let rescue:string|null=null;
 try { rescue = localStorage.getItem(rescueKey); } catch { /* storage unavailable */ }
 let raw:string|null=null;
 try {
  raw = localStorage.getItem(storageKey);
  if (!raw) return {resume:blank(), warning:'', rescue};
  const migrated = migrate(JSON.parse(raw));
  if (isResume(migrated)) return {resume:migrated, warning:'', rescue};
 } catch { /* fall through: preserve the unreadable draft below instead of losing it */ }
 if (raw) { try { localStorage.setItem(rescueKey, raw); } catch { /* best effort */ } rescue = raw; }
 return {resume:blank(), warning: raw ? 'Your saved draft could not be read by this version of the app. Download it below before you continue, so your earlier work is not lost.' : 'Browser storage is unavailable. Your work will not be saved automatically — download a backup regularly.', rescue};
}
const start=initial();
function App(){
 const [resume,setResume]=useState<Resume>(start.resume); const [page,setPage]=useState<'home'|'builder'>('home'); const [tab,setTab]=useState('personal'); const [saveState,setSaveState]=useState(start.warning?'Storage needs attention':'Saved on this device'); const [message,setMessage]=useState(start.warning); const [rescue,setRescue]=useState(start.rescue); const [dirty,setDirty]=useState(false); const [mobilePreview,setMobilePreview]=useState(false); const [menu,setMenu]=useState(false); const file=useRef<HTMLInputElement>(null);
 const update=(patch:Partial<Resume>)=>{setResume(old=>({...old,...patch}));setDirty(true);setSaveState('Saving…');};
 useEffect(()=>{if(!dirty)return;const timer=setTimeout(()=>{try{localStorage.setItem(storageKey,JSON.stringify(resume));setSaveState('Saved on this device');}catch{setSaveState('Not saved — download a backup');}},350);return()=>clearTimeout(timer);},[resume,dirty]);
 useEffect(()=>{const persist=()=>{if(dirty)try{localStorage.setItem(storageKey,JSON.stringify(resume));}catch{/* UI already offers backup */}};window.addEventListener('pagehide',persist);return()=>window.removeEventListener('pagehide',persist);},[resume,dirty]);
 const downloadBackup=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(resume,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${resume.name || 'my'}-resume.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const downloadRescue=()=>{if(!rescue)return;const url=URL.createObjectURL(new Blob([rescue],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='unreadable-draft-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const discardRescue=()=>{try{localStorage.removeItem(rescueKey);}catch{/* best effort */}setRescue(null);};
 const importBackup=async(event:React.ChangeEvent<HTMLInputElement>)=>{const selected=event.target.files?.[0];if(!selected)return;try{if(selected.size>2000000)throw Error('Please choose a backup smaller than 2 MB.');const data:unknown=migrate(JSON.parse(await selected.text()));if(!isResume(data))throw Error('This is not a valid ResumeStride JSON backup. PDF and Word import are not available yet.');if(dirty || resume.name){if(!window.confirm('Replace the current draft with this backup? Download a backup first if you want to keep it.'))return;}update(data);setPage('builder');setMessage('Backup imported. Review your details before downloading.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to import this file.');}finally{event.target.value='';}};
 const print=()=>{setMessage('Choose “Save as PDF” in the print dialog. Turn off browser headers and footers for a clean resume.');window.print();};
 const begin=()=>{setPage('builder');window.scrollTo(0,0);};
 const field=(label:string,key:'name'|'headline'|'email'|'phone'|'location'|'website'|'summary'|'skills',placeholder:string,multiline=false)=><label className={multiline?'field full':'field'}>{label}{multiline?<textarea dir="auto" rows={key==='summary'?5:3} maxLength={50000} value={resume[key]} placeholder={placeholder} onChange={event=>update({[key]:event.target.value})}/>:<input dir="auto" maxLength={50000} value={resume[key]} placeholder={placeholder} onChange={event=>update({[key]:event.target.value})}/>}</label>;
 const selectedSection=resume.sections.find(section=>section.id===tab);
 const completion=[resume.name,resume.headline,resume.summary,resume.sections.some(section=>section.entries.some(item=>item.title)),resume.skills].filter(Boolean).length;
 return <><style>{`@page {size: ${resume.paper}; margin: 15mm;}`}</style><input ref={file} type="file" accept=".json,application/json" hidden onChange={importBackup}/>
 <header className="site-header"><button className="brand" onClick={()=>setPage('home')} aria-label="ResumeStride home"><span className="brand-icon"><FileText size={22}/></span>Resume<span className="brand-light">Stride</span><span className="beta">BETA</span></button>{page==='home'?<><nav className={menu?'nav open':'nav'}><a href="#how-it-works">How it works</a><a href="#templates">Templates</a><a href="#pricing">Pricing</a></nav><button className="button header-cta" onClick={begin}>{resume.name?'Continue my resume':'Build my resume'}<ArrowRight size={16}/></button><button className="icon-button mobile-menu" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}><Menu/></button></>:<div className="header-actions"><span className="save-status" role="status"><CheckCircle2 size={15}/>{saveState}</span><button className="button outline backup" onClick={downloadBackup}><Download size={16}/>Backup</button><button className="button" onClick={print}><Download size={16}/>Print / PDF</button></div>}</header>
 {message&&<div className="notice" role="status">{message}<button aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {rescue&&<div className="notice" role="status">An earlier draft on this device could not be loaded and has been kept separately so it isn’t lost.<button className="text-button" onClick={downloadRescue}><Download size={14}/>Download it</button><button aria-label="Discard the unreadable draft" onClick={discardRescue}><X size={16}/></button></div>}
 {page==='home'?<main>
 <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> YOUR EXPERIENCE. YOUR NEXT CHAPTER.</div><h1>Good things start<br/>with a great <em>resume.</em></h1><p className="hero-description">You bring the experience. We’ll help you put it into words.<br className="desktop-break"/> Create a resume that feels like you, wherever you’re headed.</p><div className="hero-actions"><button className="button large" onClick={begin}>Build my resume<ArrowRight size={19}/></button><button className="text-button" onClick={()=>file.current?.click()}><Upload size={17}/>Import a backup</button></div><div className="hero-promises"><span><Check size={15}/>Free PDF printing</span><span><Check size={15}/>No card needed</span><span><Check size={15}/>No sign-up</span></div><div className="audience-note"><div className="avatar-stack"><span>AM</span><span>SK</span><span>JL</span></div><div>Every background. Every ambition.<small>Made for your next opportunity.</small></div></div></div>
 <div className="hero-art" aria-label="Example resume illustration"><div className="art-orbit"/><div className="floating-note"><span className="small-check"><Check size={16}/></span>Your next chapter looks good.</div><div className="example-document"><ResumePreview resume={example()}/></div><div className="floating-format"><span><LayoutTemplate size={20}/></span><div>Your story, beautifully presented<small>Clean layouts. A confident first impression.</small></div></div><span className="art-spark">✳</span></div>
 </section>
 <section className="trust-strip"><span>A little less stress. A lot more possibility.</span><div><Globe2 size={18}/>Built for every career</div><div><ShieldCheck size={18}/>Your information stays yours</div><div><FileText size={18}/>A4 & US Letter</div></section>
 <section className="section steps-section" id="how-it-works"><div className="section-intro"><span className="eyebrow">FROM A BLANK PAGE TO WHAT’S NEXT</span><h2>Big next step. Simple first steps.</h2><p>Less time fixing margins. More time finding your next opportunity.</p></div><div className="steps-grid">{[{icon:<UserRound/>,title:'Start with your story',text:'Add your experience, education, and skills. Starting out or changing direction? There’s room for your story.'},{icon:<LayoutTemplate/>,title:'Make it feel like you',text:'Choose a clean template, pick a color, and see every change as you make it.'},{icon:<Download/>,title:'Take the next step',text:'Print or save your resume as a PDF, free. Keep a backup and come back whenever you need.'}].map((step,i)=><div className="step" key={step.title}><div className="step-top"><span className="step-icon">{step.icon}</span><span className="step-number" aria-hidden="true">0{i+1}</span></div><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section>
 <section className="section templates-section" id="templates"><div className="section-intro"><span className="eyebrow">LET YOUR EXPERIENCE STAND OUT</span><h2>Three layouts. Endless possibilities.</h2><p>Thoughtful, readable designs for any profession.</p></div><div className="templates-grid">{(['modern','classic','minimal'] as const).map((template,i)=><button className="template-card" key={template} onClick={()=>{update({template});begin();}}><div className={`template-thumbnail thumb-${template}`}><ResumePreview resume={{...example(),template}}/></div><div className="template-label"><div><strong>{['Modern','Classic','Minimal'][i]}</strong><small>{['A fresh, confident introduction','Timeless, polished, professional','Your experience takes center stage'][i]}</small></div><ArrowRight size={18}/></div></button>)}</div></section>
 <section className="section pricing-section" id="pricing"><div><span className="eyebrow">A FAIR START, FOR EVERYONE</span><h2>Your next opportunity<br/>shouldn’t start with a paywall.</h2><p>The core builder is free during beta. No card, no trial countdown,<br/>and no automatic charges.</p></div><div className="price-card"><span className="price-tag">FREE BETA</span><div className="price">$0 <span>to build your resume</span></div><p><Check size={16}/>All three templates and live preview</p><p><Check size={16}/>Unlimited PDF printing</p><p><Check size={16}/>Local autosave and downloadable backups</p><button className="button" onClick={begin}>Let’s build your resume<ArrowRight size={17}/></button></div></section>
 <footer><span className="footer-brand">resumestride</span><span>For wherever life takes you next.</span><small>Local beta · Your draft is stored in this browser. Questions? <a href="mailto:support@resumestride.com">support@resumestride.com</a></small></footer>
 </main>:<main className="builder"><aside className="builder-sidebar"><button className="back-link" onClick={()=>setPage('home')}><ArrowLeft size={15}/>Back to home</button><h2>Your resume</h2><p className="muted">One step closer to what’s next.</p><div className="progress-track"><span style={{width:`${completion*20}%`}}/></div><small>{completion} of 5 essentials added</small><nav aria-label="Resume sections"><button className={tab==='personal'?'active':''} onClick={()=>setTab('personal')}><UserRound size={18}/>Personal details</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}><FileText size={18}/>Profile & skills</button>{resume.sections.map(section=><button className={tab===section.id?'active':''} key={section.id} onClick={()=>setTab(section.id)}><GripVertical size={18}/>{section.title || 'Untitled section'}</button>)}<button disabled={resume.sections.length>=30} title={resume.sections.length>=30?'Maximum of 30 sections reached':undefined} onClick={()=>{const id=crypto.randomUUID();update({sections:[...resume.sections,{id,title:'Additional experience',entries:[entry()]}]});setTab(id);}}><Plus size={18}/>Add a section</button><button className={tab==='design'?'active':''} onClick={()=>setTab('design')}><LayoutTemplate size={18}/>Design & format</button></nav><div className="sidebar-tip"><ShieldCheck size={19}/><strong>Your story stays yours.</strong><p>Your draft is saved in this browser, on this device. Download a backup before switching devices or clearing browser data.</p><button className="text-button" onClick={downloadBackup}>Save a backup<ArrowDown size={14}/></button></div><button className="back-link" onClick={()=>file.current?.click()}><Upload size={15}/>Import JSON backup</button></aside>
 <section className={`editor-panel ${mobilePreview?'hide-mobile':''}`}><div className="editor-heading"><span className="eyebrow">MAKE YOUR NEXT MOVE</span><h1>{tab==='personal'?'Let’s start with you.':tab==='profile'?'Tell your story.':tab==='design'?'Make it your own.':selectedSection?.title || 'Your experience'}</h1><p>{tab==='personal'?'The basics that help someone get in touch. All fields are optional.':tab==='profile'?'A little context goes a long way. Keep it clear and true to you.':tab==='design'?'Simple choices. A polished result.':'Every kind of experience counts. Add what matters to your next role.'}</p></div>
 {tab==='personal'&&<><div className="field-grid">{field('Full name','name','e.g. Alex Morgan')}{field('Professional title','headline','Your role or the opportunity you want')}{field('Email','email','you@example.com')}{field('Phone','phone','Include your country code')}{field('Location','location','City, region, or country')}{field('Website or professional profile','website','Portfolio, LinkedIn, or personal website')}</div><div className="helper-box"><Globe2 size={20}/><div><strong>At home, anywhere.</strong><p>Use your preferred name and local contact format. No postal code or street address required.</p></div></div><button className="button next-button" onClick={()=>setTab('profile')}>Continue to profile<ArrowRight size={17}/></button></>}
 {tab==='profile'&&<div className="field-grid">{field('Professional profile','summary','Introduce your experience, strengths, and the contribution you want to make.',true)}<p className="field-hint">New to work? Include coursework, volunteering, personal projects, or transferable skills.</p>{field('Skills & languages','skills','e.g. Project coordination, Customer service, Excel, English (fluent)',true)}<label className="field">Profile section heading<input maxLength={200} value={resume.profileHeading} placeholder="Profile" onChange={event=>update({profileHeading:event.target.value})}/></label><label className="field">Skills section heading<input maxLength={200} value={resume.skillsHeading} placeholder="Skills & languages" onChange={event=>update({skillsHeading:event.target.value})}/></label><div className="helper-box"><Sparkles size={20}/><div><strong>Specific is stronger than impressive.</strong><p>Use real examples and only include skills you can confidently discuss. AI writing tools are planned; this beta keeps you in control.</p></div></div></div>}
 {selectedSection&&<><label className="field">Section title<input maxLength={50000} value={selectedSection.title} onChange={event=>update({sections:resume.sections.map(section=>section.id===tab?{...section,title:event.target.value}:section)})}/></label><div className="section-actions"><button className="text-button" disabled={resume.sections[0]?.id===tab} onClick={()=>{const sections=[...resume.sections];const i=sections.findIndex(s=>s.id===tab);[sections[i-1],sections[i]]=[sections[i],sections[i-1]];update({sections});}}>↑ Move section up</button><button className="text-button danger" onClick={()=>{if(window.confirm('Delete this section and its entries?')){update({sections:resume.sections.filter(section=>section.id!==tab)});setTab('personal');}}}><Trash2 size={14}/>Delete section</button></div>{selectedSection.entries.map((item,i)=><div className="entry-form" key={item.id}><div className="entry-form-heading"><strong>Entry {i+1}</strong><button className="icon-button" aria-label={`Remove entry ${i+1}`} onClick={()=>{if(window.confirm('Remove this entry?'))update({sections:resume.sections.map(section=>section.id===tab?{...section,entries:section.entries.filter(e=>e.id!==item.id)}:section)});}}><Trash2 size={16}/></button></div><div className="field-grid">{(['title','organization','location','dates','description'] as const).map(key=><label className={`field ${key==='description'?'full':''}`} key={key}>{({title:'Role, qualification, or project',organization:'Organization or institution',location:'Location (optional)',dates:'Dates (your preferred format)',description:'Details (one point per line)'})[key]}{key==='description'?<textarea dir="auto" rows={5} maxLength={50000} value={item[key]} onChange={event=>update({sections:resume.sections.map(section=>section.id===tab?{...section,entries:section.entries.map(e=>e.id===item.id?{...e,[key]:event.target.value}:e)}:section)})}/>:<input dir="auto" maxLength={50000} value={item[key]} onChange={event=>update({sections:resume.sections.map(section=>section.id===tab?{...section,entries:section.entries.map(e=>e.id===item.id?{...e,[key]:event.target.value}:e)}:section)})}/>}</label>)}</div></div>)}<button className="button outline" disabled={selectedSection.entries.length>=100} title={selectedSection.entries.length>=100?'Maximum of 100 entries per section reached':undefined} onClick={()=>update({sections:resume.sections.map(section=>section.id===tab?{...section,entries:[...section.entries,entry()]}:section)})}><Plus size={16}/>Add an entry</button></>}
 {tab==='design'&&<div className="design-options"><label className="field">Template<select value={resume.template} onChange={e=>update({template:e.target.value as Resume['template']})}><option value="modern">Modern</option><option value="classic">Classic</option><option value="minimal">Minimal</option></select></label><label className="field">Paper size<select value={resume.paper} onChange={e=>update({paper:e.target.value as Resume['paper']})}><option>A4</option><option>Letter</option></select></label><label className="field">Accent color<input type="color" value={resume.accent} onChange={e=>update({accent:e.target.value})}/></label><label className="field">Writing direction<select value={resume.direction} onChange={e=>update({direction:e.target.value as Resume['direction']})}><option value="ltr">Left to right</option><option value="rtl">Right to left</option></select></label><label className="field">Resume language code<input maxLength={35} value={resume.language} placeholder="en" onChange={e=>update({language:e.target.value.replace(/[^A-Za-z0-9-]/g,'').slice(0,35)})}/></label><p className="field-hint">Write in any language. Section titles, the Profile and Skills headings (in Profile & skills), and the resume’s language code are all editable. The language code (e.g. en, fr, ar, ne) helps screen readers and print correctly; it does not translate the interface, which is currently English.</p><button className="button outline" onClick={()=>{if(window.confirm('Replace your draft with a fictional example? Save a backup first to keep your work.')){update(example());setMessage('Fictional example loaded. Replace all details with your own.');}}}>Load an example</button><button className="text-button danger" onClick={()=>{if(window.confirm('Clear this resume and start again? This cannot be undone.')){update(blank());setTab('personal');}}}><RotateCcw size={16}/>Start a blank resume</button></div>}
 </section><section className={`preview-panel ${!mobilePreview?'hide-mobile':''}`}><div className="preview-toolbar"><span><span className="live-dot"/>LIVE PREVIEW</span><span>{resume.paper}<ChevronDown size={13}/></span></div><div className={`paper-container paper-${resume.paper}`}><ResumePreview resume={resume}/></div><p className="preview-caption"><ShieldCheck size={14}/>The faint lines mark approximately where each printed page ends.</p></section><button className="mobile-preview-toggle button" onClick={()=>setMobilePreview(!mobilePreview)}>{mobilePreview?'Back to editing':'Preview resume'}<FileText size={16}/></button></main>}
 <div className="print-only"><ResumePreview resume={resume}/></div></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
